import Head from 'next/head';

import AboutMeSection from '../components/AboutMeSection';
import ContactMeSection from '../components/ContactMeSection.js';
import IntroSection from '../components/IntroSection';
import MyWorkSection from '../components/MyWorkSection';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <IntroSection />
        <AboutMeSection />
        <MyWorkSection />
        <ContactMeSection />
      </main>
    </>
  )
};
