import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.intro}>
          <div className={styles.introWindow}>
            <div className={styles.windowTop}>
              <div className={styles.buttonSelection}>
                <div className={styles.red}></div>
                <div className={styles.yellow}></div>
                <div className={styles.green}></div>
              </div>

              <p className={styles.windowTitle}>
                intro.txt
              </p>

              <div className={styles.buttonSelectionFiller}>
                <div className={styles.red}></div>
                <div className={styles.yellow}></div>
                <div className={styles.green}></div>
              </div>
            </div>

            <div className={styles.introContent}>
              <h1 className={styles.name}>John Climie</h1>
              <h2 className={styles.careerName}>Full-Stack Web Developer</h2>

              <hr />

              <div className={styles.introLinks}>
                <h2>About Me</h2>
                <h2>My Work</h2>
                <h2>Contact</h2>
              </div>
              <h2 className={styles.resumeLink}>Resume</h2>
            </div>
          </div>
        </section>

        <section className={styles.aboutMe}>
          <div className={styles.menuBar}>
            <div className={styles.menuId}>
              <p>JC</p>
              <p>About Me</p>
            </div>

            <div className={styles.menuTime}>
              <p>Wed Jan 4 2:16 PM</p>
            </div>
          </div>
          
          <div className={styles.aboutMeContent}>
            <div className={styles.aboutMeGrid}>
              <div className={styles.aboutMeTxt}>
                <div className={styles.lightWindowTop}>
                    <div className={styles.buttonSelection}>
                    <div className={styles.red}></div>
                    <div className={styles.yellow}></div>
                    <div className={styles.green}></div>
                  </div>

                  <p className={styles.windowTitle}>
                    aboutme.txt
                  </p>

                  <div className={styles.buttonSelectionFiller}>
                    <div className={styles.red}></div>
                    <div className={styles.yellow}></div>
                    <div className={styles.green}></div>
                  </div>
                </div>
                
                <div>
                  <p></p>
                </div>

              </div>

              <div className={styles.skillsTxt}>
                <div className={styles.lightWindowTop}>
                      <div className={styles.buttonSelection}>
                      <div className={styles.red}></div>
                      <div className={styles.yellow}></div>
                      <div className={styles.green}></div>
                    </div>

                    <p className={styles.windowTitle}>
                      skills.txt
                    </p>

                    <div className={styles.buttonSelectionFiller}>
                      <div className={styles.red}></div>
                      <div className={styles.yellow}></div>
                      <div className={styles.green}></div>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
